# Generated by Django 3.1.6 on 2021-02-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Książki', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autorzy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Autor', models.CharField(max_length=50)),
                ('Publikacje', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autorzy',
            },
        ),
        migrations.AlterModelOptions(
            name='książki',
            options={'verbose_name': 'Książka', 'verbose_name_plural': 'Książki'},
        ),
    ]
