# Generated by Django 3.1.6 on 2021-02-04 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Książki', '0002_auto_20210204_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='książki',
            name='autorzy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Książki.autorzy'),
        ),
    ]
