# Generated by Django 3.1.5 on 2021-02-04 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autorzy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Autor', models.CharField(max_length=50)),
                ('Publikacje', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autorzy',
            },
        ),
        migrations.CreateModel(
            name='Kategorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Kategoria', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Kategoria',
                'verbose_name_plural': 'Kategorie',
            },
        ),
        migrations.CreateModel(
            name='Ksiazki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tytuł', models.CharField(max_length=50)),
                ('Opis', models.TextField(blank=True)),
                ('Cena', models.DecimalField(decimal_places=2, max_digits=6)),
                ('autorzy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ksiazki.autorzy')),
                ('kategoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ksiazki.kategorie')),
            ],
            options={
                'verbose_name': 'Ksiazka',
                'verbose_name_plural': 'Ksiazki',
            },
        ),
    ]
